### ISSUE TITLE
[gui error report] moving repository location to NAS

### ISSUE THREAD

**Issue by WXTux** [ipfs/ipfs-desktop#2528] opened 2023-06-24 14:54 UTC
👉️ Please describe what you were doing when this error happened.
I tried to move the repository location to a NAS. A number of files were moved and then I got the error: "cannot move repository location."

**Specifications**

- **OS**: win32 10.0.22621
- **IPFS Desktop Version**: 0.28.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: EBUSY: resource busy or locked, unlink 'D:\IPFS Repository\.ipfs\repo.lock'
```

**Comment by SgtPooki** [comment] 2023-07-01 05:17
I can't think of anything beyond the regular file transfer errors that could have caused this. Maybe some permission issues with kubo/electron process?

Hopefully the logs show something, and hopefully we're using kubo directly under the hood. I need to validate that.

**Comment by lidel** [comment] 2024-06-12 15:02
Closing as duplicate of https://github.com/ipfs/ipfs-desktop/issues/2826#issuecomment-2163268374

**Closed by lidel** 2024-06-12 15:02 UTC
Labels: kind/bug, need/author-input, need/maintainers-input, area/go-ipfs
