### ISSUE TITLE
[gui error report] SyntaxError: C:\Users\Jjuli\.ipfs\config: Unexpected token � in JSON at 

### ISSUE THREAD

**Issue by Mendel-Chodaton** [ipfs/ipfs-desktop#2076] opened 2022-03-25 15:48 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.20.2
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
SyntaxError: C:\Users\Jjuli\.ipfs\config: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.readFileSync (C:\Program Files\IPFS Desktop1\resources\app.asar\node_modules\jsonfile\index.js:52:17)
    at readConfigFile (C:\Program Files\IPFS Desktop1\resources\app.asar\src\daemon\config.js:29:13)
    at checkPorts (C:\Program Files\IPFS Desktop1\resources\app.asar\src\daemon\config.js:214:18)
    at module.exports (C:\Program Files\IPFS Desktop1\resources\app.asar\src\daemon\daemon.js:171:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startIpfs (C:\Program Files\IPFS Desktop1\resources\app.asar\src\daemon\index.js:46:17)
    at async module.exports (C:\Program Files\IPFS Desktop1\resources\app.asar\src\daemon\index.js:114:3)
    at async run (C:\Program Files\IPFS Desktop1\resources\app.asar\src\index.js:83:5)
```

**Comment by lidel** [comment] 2022-03-26 00:51
Duplicate of https://github.com/ipfs/ipfs-desktop/issues/2050, should be fixed in next week's release

**Closed by lidel** 2022-03-26 00:51 UTC
Labels: kind/bug, need/triage
