### ISSUE TITLE
Error at init

### ISSUE THREAD

**Issue by arturios** [ipfs/ipfs-desktop#1784] opened 2021-03-15 07:37 UTC
**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.14.0
- **Electron Version**: 11.2.3
- **Chrome Version**: 87.0.4280.141

**Error**

```
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:557:9)
    at execFile (child_process.js:241:17)
    at t.<computed> (electron/js2c/asar_bundle.js:5:2208)
    at C:\Users\XXXXXXXX\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:85:5
    at new Promise (<anonymous>)
    at runWindows (C:\Users\XXXXXXXX\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:84:10)
    at run (C:\Users\XXXXXXXX\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:108:12)
    at firstTime (C:\Users\XXXXXXXX\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:79:21)
    at module.exports (C:\Users\XXXXXXXX\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:56:3)
```

**Comment by lidel** [comment] 2021-05-05 00:59
ipfs-on-path leftover handling should be fixed in  [v0.15.0](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0), please update manually to the latest version and reopen if the issue is still present.

**Closed by lidel** 2021-05-05 00:59 UTC
