### ISSUE TITLE
[gui error report] Error: ENOENT: no such file or directory, open 'D:\file\IPFS Desktop\res

### ISSUE THREAD

**Issue by satish0369** [ipfs/ipfs-desktop#2850] opened 2024-08-15 05:32 UTC
- **Desktop**: 0.37.0
- **OS**: win32 10.0.22631 x64
- **Electron**: 31.0.1
- **Chrome**: 126.0.6478.36

```
Error: ENOENT: no such file or directory, open 'D:\file\IPFS Desktop\resources\app.asar.unpacked\node_modules\kubo\package.json'
    at Object.readFileSync (node:fs:448:20)
    at t.readFileSync (node:electron/js2c/node_init:2:10245)
    at u.internalModuleReadJSON (node:electron/js2c/node_init:2:14504)
    at read (node:internal/modules/package_json_reader:56:25)
    at readPackage (node:internal/modules/package_json_reader:141:10)
    at resolveExports (node:internal/modules/cjs/loader:595:15)
    at Module._findPath (node:internal/modules/cjs/loader:676:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1138:27)
    at s._resolveFilename (node:electron/js2c/browser_init:2:120699)
    at Module._load (node:internal/modules/cjs/loader:993:27)
```

**Comment by lidel** [comment] 2024-09-11 20:24
@satish0369  this activity looks like AI generated spam (`D:\file\`, https://github.com/satish0369/https-github.com-vaibs28-Secure-File-Sharing-Blockchain), closing. 
If you are a real human, please open a new issue explaining how to reproduce your error.

**Closed by lidel** 2024-09-11 20:24 UTC
Labels: kind/bug, need/triage
