### ISSUE TITLE
bug: OS-level protocol handler (Ubuntu/Windows): opens the app but does nothing

### ISSUE THREAD

**Issue by ghost** [ipfs/ipfs-desktop#1549] opened 2020-06-14 04:50 UTC
- OS: Linux (Ubuntu 20.04)
 - Version of IPFS Desktop [e.g. 0.11.1]
1b58b62
**Describe the bug**
Using the dweb/ipfs link from https://winworldpc.com/download/4112c2a0-7118-c39a-11c3-a4e284a2c3a5 doesn't have any effect or feedback from the IPFS desktop app.

(They're also hiding the IPFS link with Javascript, but that's a different problem)

**To Reproduce**
Open dweb://ipfs/QmSDPa5pfSNCxnKv2ybFio2oKvndX6hCbtmg7NNbNhraHe/BeOS%205.0%20Professional.7z in Firefox after installing the ipfs-desktop client via dpkg
![image](https://user-images.githubusercontent.com/159567/84584969-b7f19880-ae4d-11ea-8ed3-b0083697156f.png)
Click on 'Open Link'

App opens but there's no feedback
![image](https://user-images.githubusercontent.com/159567/84584986-e7a0a080-ae4d-11ea-8b51-94b478ff2bcc.png)

**Expected behavior**
Some kind of feedback: "File added", "File unavailable", whatever.

** Sidenote **

Your template here says this:
```
ATTACH LOGS

If possible:
1. Go to `Advanced` → `Open Logs Directory`
2. Find `*.log` files
3. Attach `error.log` and `combined.log` to this issue.
```

But there doesn't seem to be an 'Advanced' anywhere in the UI.

**Comment by jessicaschilling** [comment] 2020-07-01 16:23
@lidel @rafaelramalho19 or @olizilla -- might you be able to triage? Thank you!

**Comment by olizilla** [comment] 2020-07-01 18:18
@voltagex thanks for this detailed report! I'll take a look. Thanks for the note about the issue template too. The advanced menu is only accessible on linux flavours that show a dock / task bar icon like thing. We need a solution for that too, see #1153

**Comment by lidel** [comment] 2020-10-12 19:37
@voltagex is this still a problem on Ubuntu after you update to [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2)?

**Comment by voltagex** [comment] 2020-10-12 23:18
Will spin up a VM and test tonight.

**Comment by voltagex** [comment] 2020-10-15 04:34
Getting back to this - yes, there's still no indication that anything happened with the link on v0.13.2.

**Comment by voltagex** [comment] 2020-10-15 04:37
@lidel I can also reproduce this on Windows. After installing the desktop app and using the dweb link I originally posted, I get this: 
![image](https://user-images.githubusercontent.com/159567/96077694-347bad00-0efc-11eb-8094-25859154a603.png)

It's not easy for me to take an Ubuntu screenshot, but it's not blank there (still no feedback though)

**Comment by lidel** [comment] 2020-10-15 11:39
Thank you @voltagex! This is very useful.

We will prioritize fix for this, could be done as a part of https://github.com/ipfs-shipyard/ipfs-desktop/issues/1646

**Comment by hacdias** [comment] 2022-01-28 15:06
An update on this: I will work on #1646 and then debug this on a Linux and Windows VM. It seems to be working well on macOS. If anyone is having issues on macOS too, please let me know.

**Comment by SgtPooki** [comment] 2023-07-03 23:31
i just tested this by visiting the following URLs in safari on macOS, and while I get the prompt to open in ipfs-desktop, I do not see anything happen in IPFS desktop:

* dweb://ipfs/QmdmQXB2mzChmMeKY47C43LxUdg1NDJ5MWcKMKxDu7RgQm
* dweb://ipfs/QmSDPa5pfSNCxnKv2ybFio2oKvndX6hCbtmg7NNbNhraHe/BeOS%205.0%20Professional.7z
* dweb://ipfs/QmSnuWmxptJZdLJpKRarxBMS2Ju2oANVrgbr2xWbie9b2D
* dweb://ipfs/QmQi7RK4b7GckY56yKWUmR5ET4fq7z6ppRZ1nXbKN9P9Ss?filename=Asset%202.png -- have locally

**Closed** 2024-06-13 21:56 UTC
Labels: kind/bug, help wanted, P1, area/windows, area/linux, need/analysis
