### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: Error: open C:\Project\DEX\AR

### ISSUE THREAD

**Issue by goblintrum** [ipfs/ipfs-desktop#2294] opened 2022-10-10 17:08 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.23.0
- **Electron Version**: 19.0.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: Error: open C:\Project\DEX\ARBITRUM\swapr-dapp\.ipfs\config: The system cannot find the path specified.
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:158:9)
    at async getIpfsd (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:63:7)
    at async startDaemon (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:210:17)
    at async startIpfs (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:48:17)
    at async setupDaemon (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:116:3)
    at async run (C:\Program Files\IPFS Desktop\resources\app.asar\src\index.js:85:5)
```

**Comment by SgtPooki** [comment] 2022-10-13 21:46
duplicate of https://github.com/ipfs/ipfs-desktop/issues/2295

**Closed by SgtPooki** 2022-10-13 21:46 UTC
Labels: kind/bug, need/triage
