### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by tiannalu1229** [ipfs/ipfs-desktop#2027] opened 2022-03-13 14:41 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.20.1
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.0
Repo version: 12
System version: amd64/darwin
Golang version: go1.16.12
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 1 migrations, downloading.
Downloading migration: fs-repo-11-to-12...
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Error fetching: exceeded number of retries. last error was http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions": dial tcp 128.242.240.157:443: i/o timeout

    at errorTemplate (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:78:49)
    at Object.loadWindow (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:115:26)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/daemon.js:124:23
    at Socket.listener (/Applications/IPFS Desktop.app/Contents/Resources/app.

**Comment by lidel** [comment] 2022-03-14 20:30
Duplicate of https://github.com/ipfs/ipfs-desktop/issues/2023

**Closed by lidel** 2022-03-14 20:30 UTC
Labels: kind/bug, need/triage
