### ISSUE TITLE
Is the local IPFS repo automatically made public?

### ISSUE THREAD

**Issue by ruifortes** [ipfs/ipfs-desktop#2058] opened 2022-03-22 20:10 UTC
Hello.~
I have IPFS-Desktop as well as IPFS-Companion (two distinct repos) and I just found out that all files are publicly accessible.
If I add a file in either IPFS-Desktop or IPFS-Companion it becomes immediately accessible by anyone with the CID.
Is this so? Is it configurable? If not, why?
Thanks

**Comment by lidel** [comment] 2022-03-23 00:09
Your description is correct: by default, everything you add to "Files" in IPFS Desktop  will be available to other peers. They can fetch it from you if they ask for a specific CID, because your node will announce on the public DHT which CIDs it can provide, and they can discover you that way.

You can change this behavior by editing config and changing [`Reprovider.Strategy`](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#reproviderstrategy). If you  set it to "pinned", your node will only announce things you explicitly pinned locally, making it harder for other peers to learn about your CIDs (but not impossible).  Even if you set `Reprovider.Strategy` to `pinned`, peers can always connect to you directly and ask for a CID over bitswap.

I am closing this as this is not a bug report, and support questions belong to our discussion forum at https://discuss.ipfs.io/c/help/13 :)

**Closed by lidel** 2022-03-23 00:09 UTC

**Comment by ruifortes** [comment] 2022-03-26 10:43
I would feel safer if a leaked CID wouldn't compromise so much :-\
