### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by dragonheadbrother** [ipfs/ipfs-desktop#1786] opened 2021-03-21 09:45 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.14.0
- **Electron Version**: 11.2.3
- **Chrome Version**: 87.0.4280.141

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (D:\Program Files\IPFS Desktop\resources\app.asar\src\tray.js:216:30)
    at MenuItem.click (electron/js2c/browser_init.js:73:1683)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2343)
```

**Comment by lidel** [comment] 2021-05-05 00:55
Duplicate of https://github.com/ipfs/ipfs-desktop/issues/1773, please see fix suggested there.

**Closed by lidel** 2021-05-05 00:55 UTC
