### ISSUE TITLE
Recover from unresponsive webui in webContents

### ISSUE THREAD

**Issue by lialosiu** [ipfs/ipfs-desktop#1865] opened 2021-06-30 02:41 UTC
`QmfFLsxJsviSncH5LGkwss53Vn2v6ebZYb3bJYtZ5P25HM`

this is the a sample file hash.

browse this file hash will freeze the window, and got high cpu usage.

and the log said: `error: [web ui] unresponsive: [object Object]`

**Comment by lidel** [comment] 2021-07-06 14:27
`QmfFLsxJsviSncH5LGkwss53Vn2v6ebZYb3bJYtZ5P25HM`  has no diallble providers, so UI is stuck at content lookup phase.

Closing this as a  duplicate of https://github.com/ipfs/ipfs-webui/issues/1794

**Comment by lidel** [comment] 2021-07-06 14:32
... actually, IPFS Desktop should detect unresponsive webui window and recover from it!

We could listen for [`unresponsive`](https://www.electronjs.org/docs/api/web-contents#event-unresponsive) event:

```js
window.on('unresponsive', () => {
  // destroy webui window and open new one
})
```

There is also [`responsive`](https://www.electronjs.org/docs/api/web-contents#event-unresponsive) when unresponsiveness was a temporary fluke, so we most likely should do reload only when `unresponsive` is not followed by `responsive` in some period of time, eg.  ~10s

**Comment by lidel** [comment] 2022-02-08 03:12
Closed by https://github.com/ipfs/ipfs-desktop/pull/1952

**Closed by lidel** 2022-02-08 03:12 UTC
Labels: help wanted, exp/intermediate, P2, good first issue, effort/hours
