### ISSUE TITLE
HELP_IPFS Desktop still crashing_[gui error report] Error

### ISSUE THREAD

**Issue by MattJohnsonMusic** [ipfs/ipfs-desktop#2060] opened 2022-03-23 14:02 UTC
👉️ Please describe what you were doing when this error happened.
I've had this problem in the recent past…IPFS Desktop app crashing. SO, I've spent the last several days upgrading/updating my ENTIRE Mac system. Main computer is Mid-2010 Mac Pro tower. I've been able to install macOS 10.15.7 (Catalina)…the fastest I can put on my machine.

All of this hassle/headache, just so I could reinstall IPFS Desktop app…hoping it would finally be stable and work. NOPE!!

So once again, HELP, please? 
Matt

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.20.3
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
Error
    at errorTemplate (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:78:49)
    at loadWindow (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:115:26)
    at module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:120:3)
    at startIpfsWithLogs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/daemon.js:158:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/daemon.js:174:17)
    at async startIpfs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:46:17)
    at async module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:114:3)
    at async run (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/index.js:83:5)
```

**Comment by lidel** [comment] 2022-03-23 14:23
Thank you for reporting. This looks like a duplicate of https://github.com/ipfs/ipfs-desktop/issues/2038
Let's continue there.

**Closed by lidel** 2022-03-23 14:23 UTC
Labels: kind/bug, need/triage
