### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by do-nothing** [ipfs/ipfs-desktop#2130] opened 2022-05-09 09:03 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.20.5
- **Electron Version**: 18.0.3
- **Chrome Version**: 100.0.4896.75

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.2
Repo version: 12
System version: amd64/windows
Golang version: go1.16.15
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 1 migrations, downloading.
Downloading migration: fs-repo-11-to-12...
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Error fetching: exceeded number of retries. last error was http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions": dial tcp 192.133.77.189:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Fetching with IPFS: "fs-repo-11-to-12/versions"
Error fetching: context deadline exceeded
could not get latest version of migration fs-repo-11-to-12: 2 errors occurred:
	* exceeded number of

**Comment by SgtPooki** [comment] 2022-05-09 19:15
Thanks for submitting this error report! Is that the end of the error log, or is there more you can share? 

This seems to be a duplicate of https://github.com/ipfs/ipfs-desktop/issues/2099#issuecomment-1108903948, can you follow the steps mentioned there? You can follow along on an issue for improving this error messaging at  https://github.com/ipfs/go-ipfs/issues/8911.

**Closed by SgtPooki** 2022-05-09 19:15 UTC
Labels: kind/bug, status/duplicate
