### ISSUE TITLE
Taskbar icon not working

### ISSUE THREAD

**Issue by Dominiquini** [ipfs/ipfs-desktop#2627] opened 2023-09-14 03:43 UTC
- OS: Windows 10 x64
- Version of IPFS Desktop: [0.30.2](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.30.2)

**Describe the bug**
I'm unable to right-click on the IPFS icon on the taskbar to quit the application. No menu appears. I'm only able to open the GUI with left-click!

**To Reproduce**
1. Start IPFS
2. Right-click on the icon on the taskbar
3. Nothing happens!

**Expected behavior**
Menu with options should appear!

**Screenshots**
---

**Additional context**
The icon also don't change color when I'm connected!
The version [0.30.1](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.30.1) works fine!

[combined.log](https://github.com/ipfs/ipfs-desktop/files/12604517/combined.log)
[error.log](https://github.com/ipfs/ipfs-desktop/files/12604519/error.log)

Thanks

**Comment by yatounoneko** [comment] 2023-09-16 04:28
Try to change `C:\Users\<USER NAME FILE>\AppData\Roaming\IPFS Desktop\config.json` language to `""`, is was work for me.

**Comment by Azulan** [comment] 2023-09-17 11:56
> Try to change `C:\Users\<USER NAME FILE>\AppData\Roaming\IPFS Desktop\config.json` language to `""`, is was work for me.
> 
> My guess is that this is another one of those bugs in the translation configuration.
> 
> * Version 0.30.0 started to cause the tray menu to function in a confusing way, and the migration function didn't work.
> * Version 0.30.1 fixes the migration function, but still does not fix the tray menu language problem.
> * Version 0.30.2 fixes the default language(EN?) for tray menu, but use other languages cause prevent right-clicking icons.
> 
> Seems like the language system has been screwed up since version 0.30.0 #2600 FYI

Worked for me.

**Comment by Dominiquini** [comment] 2023-09-17 15:57
Worked for me too!

Thanks.

**Comment by Azulan** [comment] 2023-09-18 01:34
@whizzzkid to be clear, it was @yatounoneko  who provided the work around and analysis. But thank you all for your hard work!

**Comment by SgtPooki** [comment] 2023-09-18 20:54
thanks for the clarification on ipfs-desktop versions and where you're seeing problems, also, providing the logs is super helpful.

I'll get on my windows machine today to start diving in, and possibly look into getting a remote windows VM that both @whizzzkid and I can look at when deploying & testing ipfs-desktop updates.

**Comment by SgtPooki** [comment] 2023-09-21 00:33
I was not able to reproduce this error on my windows 10 machine. Right clicking the taskbar icon works fine no matter what language I have selected. 

1. I tried changing languages and then right clicking: it works
2. I tried changing languages and closing ipfs-desktop, re-opening, and then right clicking the icon: it works
3. I tried pinning the icon to the task bar (instead of the windows task bar mini popout): it still works

I'm guessing an error is occurring on some machines preventing the systray menu from being set up properly.. but it's hard to find a solution if i can't reproduce.

**Comment by yatounoneko** [comment] 2023-09-24 08:03
> @SgtPooki can confirm, I am seeing a similar behaviour while using win11 in Parallels. It seems to work as expected.
> 
> <img alt="parallels" width="1705" src="https://user-images.githubusercontent.com/1895906/269483986-3de47460-63b8-4547-938b-d1e9c8e60d88.png">
> @Dominiquini @yatounoneko can you please re-check and provide a better way to reproduce this error?

I don't the language value in your `C:\Users\<USER NAME FILE>\AppData\Roaming\IPFS Desktop\config.json` config.
But I try to change config `"language": "",` to `en` or `""` is normal, if change to `en-US` or `zh-HK` or `zh-CN` will get the GUI page normal and taskbar icon not working.

**Comment by dysbulic** [comment] 2023-09-25 06:22
I was seeing the same issue on Ubuntu, and setting `language` to the empty string fixed it.

**Comment by SgtPooki** [comment] 2023-10-04 23:14
@yatounoneko thanks for the extra info! it sounds like to reproduce, setting "language" to "en-US" should trigger the error.. retrying now

**Comment by SgtPooki** [comment] 2023-10-04 23:27
Heyo! reproduced by manually setting language to "en-US" in `/Users/sgtpooki/Library/Application Support/IPFS Desktop/config.json`

thanks all.. working on fix.

**Comment by SgtPooki** [comment] 2023-10-05 00:36
The fix is out: https://github.com/ipfs/ipfs-desktop/pull/2650. It's a super simple fix for an odd behavior from i18next: it shows an error when it cannot find a file for a language, even if it successfully resolves to a file for that language.

**Closed** 2023-10-09 04:42 UTC
Labels: kind/bug, area/windows, need/author-input, need/maintainers-input, topic/windows

**Comment by SgtPooki** [comment] 2023-10-10 05:35
Note that this is still not released due to some failures with windows build in CI
