### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by deenmkkl** [ipfs/ipfs-desktop#2643] opened 2023-09-27 23:46 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32 10.0.22621
- **IPFS Desktop Version**: 0.30.2
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Initializing daemon...
Kubo version: 0.22.0
Repo version: 14
System version: amd64/windows
Golang version: go1.19.12
Error: lock C:\Users\Demzie\.ipfs\repo.lock: someone else has the lock


    at errorTemplate (C:\Users\Demzie\Desktop\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:78:49)
    at Object.loadWindow (C:\Users\Demzie\Desktop\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:129:26)
    at startIpfsWithLogs (C:\Users\Demzie\Desktop\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:191:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startDaemon (C:\Users\Demzie\Desktop\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:216:27)
    at async startIpfs (C:\Users\Demzie\Desktop\IPFS Desktop\resources\app.asar\src\daemon\index.js:49:17)
    at async IpcMainImpl.restartIpfs (C:\Users\Demzie\Desktop\IPFS Desktop\resources\app.asar\src\daemon\index.js:103:5)
```

**Comment by SgtPooki** [comment] 2023-10-04 22:39
duplicate of https://github.com/ipfs/ipfs-desktop/issues/2644

**Closed by SgtPooki** 2023-10-04 22:39 UTC
Labels: kind/bug, need/triage
