### ISSUE TITLE
Crash when selecting about-->update in task icon (win10)

### ISSUE THREAD

**Issue by fullofentropy** [ipfs/ipfs-desktop#1822] opened 2021-05-12 17:02 UTC
Please describe what you were doing when this error happened.
1) installed ipfs using chocolatey install
2) isntalled ipfs-desktop using chocolatay install
3) run ipfs desktop but get an error, try to run ipfs command line and get error stating repo is newer than the deamon and needs to be udpated.
4) uninstall ipfs 
5) execute ipfs-desktop
6) right click the ipfs desktop task icon in the lower right --> about-->check for updates
7) crash and click to report the issue.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.15.0
- **Electron Version**: 12.0.5
- **Chrome Version**: 89.0.4389.128

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (C:\Users\rb991c\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\tray.js:216:30)
    at MenuItem.click (electron/js2c/browser_init.js:73:1742)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

**Comment by fullofentropy** [comment] 2021-05-12 17:40
This issue is repeatable, i'm new to IPFS, it worked the first time I installed it no issues... until I rebooted the computer.  

```
ipfs daemon
Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/windows
Golang version: go1.14.4

Error: Your programs version (10) is lower than your repos (11).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.
```

**Comment by lidel** [comment] 2021-05-21 13:38
@fullofentropy I believe this is a duplicate of https://github.com/ipfs/ipfs-desktop/issues/1773, pelase check if workaround from https://github.com/ipfs/ipfs-desktop/issues/1773#issuecomment-789294333 work for you, if not, we will have proper fix when https://github.com/ipfs/ipfs-desktop/pull/1826

**Closed by lidel** 2021-05-21 13:38 UTC
Labels: need/triage

**Comment by fullofentropy** [comment] 2021-05-21 14:34
I'll have to give it a try to see that fixes it when I get the time, for now I shifted to spawning a docker ipfs node and am exploring/hosting sites using this and have not run into any issues other than trying to automate the upload and pinning SSG's to it, but that is out of scope of this thread.
