### ISSUE TITLE
[gui error report] Error: The system cannot find the path specified.

### ISSUE THREAD

**Issue by GitMarkalsoHub** [ipfs/ipfs-desktop#2859] opened 2024-09-13 13:07 UTC
- **Desktop**: 0.38.0
- **OS**: win32 10.0.19045 x64
- **Electron**: 31.0.1
- **Chrome**: 126.0.6478.36

```
Error: The system cannot find the path specified.

    at errorTemplate (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:78:49)
    at Object.loadWindow (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:129:26)
    at startIpfsWithLogs (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:191:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startDaemon (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:216:27)
    at async startIpfs (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:49:17)
    at async restartIpfs (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:103:5)
    at async C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\index.js:36:5
    at async C:\Program Files\IPFS Desktop\resources\app.asar\src\context.js:105:16
```

**Comment by GitMarkalsoHub** [comment] 2024-09-13 13:09
IPFS just stopped working when I updated it.  I was running OK with previous version.  Failed on updating it.  I went back to previous version and it now failing on startup.

**Comment by lidel** [comment] 2024-10-16 21:57
Assuming duplicate of https://github.com/ipfs/ipfs-desktop/issues/2858

**Closed by lidel** 2024-10-16 21:57 UTC
Labels: kind/bug, need/triage
