### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by ldongting** [ipfs/ipfs-desktop#2121] opened 2022-04-30 15:17 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.20.5
- **Electron Version**: 18.0.3
- **Chrome Version**: 100.0.4896.75

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.2
Repo version: 12
System version: amd64/windows
Golang version: go1.16.15
Error: remove C:\Users\Administrator\.ipfs\datastore\000044.ldb: The process cannot access the file because it is being used by another process.


    at errorTemplate (D:\Program Files\IPFS\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:78:49)
    at Object.loadWindow (D:\Program Files\IPFS\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:115:26)
    at startIpfsWithLogs (D:\Program Files\IPFS\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:163:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (D:\Program Files\IPFS\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:190:17)
    at async startIpfs (D:\Program Files\IPFS\IPFS Desktop\resources\app.asar\src\daemon\index.js:46:17)
    at async module.exports (D:\Program Files\IPFS\IPFS Desktop\resources\app.asar\src\daemon\index.js:114:3)
    at async run (D:\Program Files\IPFS\IPFS Desktop\resources\app.asar\src\index.js:82:5)
```

**Comment by hacdias** [comment] 2022-05-02 12:56
Duplicate of #2120

**Closed by hacdias** 2022-05-02 12:56 UTC
Labels: kind/bug, need/triage
