### ISSUE TITLE
Pinning a folder with a large number of files times out.

### ISSUE THREAD

**Issue by MarcelInTO** [ipfs/ipfs-desktop#2238] opened 2022-08-24 15:54 UTC
- OS: Windows
- Version of IPFS Desktop: 2.15.1

I have relatively large tree of files (QmbaRnTcc4qKKuoJ31aooZApoDMNJwahYoSKxBctFmu5Rg). There are about 220,000 files organized into 220 folders with 1000 files each.

I wish to pin it.

Running the pin command on the top level folder will go away for a relatively short time and then terminate with a message indicating the operation has timed out. I can pin the individual subdirectories (of 1000 files each) OK, but it would be tedious. The interface does not allow me to select multiple directories to pin at once.

Using the CLI, I can perform "c:ipfs --api=/ip4/127.0.0.1/tcp/5001 pin add --progress --recursive QmbaRnTcc4qKKuoJ31aooZApoDMNJwahYoSKxBctFmu5Rg" and while iseems very slow and takes a long time, it does not time out.

**Expected behavior**
I am pinning a large number of files and expect the operation to take a long time. I do not want the operation to time out in an arbitrary amount of time. If the operation is working correclty, I would like it to finish the requested task  (preferably with some progress indicator like the CLI can give me).

**Comment by hacdias** [comment] 2022-09-01 13:37
Duplicate of https://github.com/ipfs/ipfs-webui/issues/1991

**Closed by hacdias** 2022-09-01 13:37 UTC
Labels: kind/bug, need/triage
