### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by book-s** [ipfs/ipfs-desktop#2122] opened 2022-04-30 17:30 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.20.5
- **Electron Version**: 18.0.3
- **Chrome Version**: 100.0.4896.75

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.2
Repo version: 12
System version: amd64/darwin
Golang version: go1.16.15
2022-05-01T01:29:22.394 0800	ERROR	cmd/ipfs	ipfs/daemon.go:430	error from node construction: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".PstoreAddSelfKeys (github.com/ipfs/go-ipfs@v0.12.2/core/node/libp2p/libp2p.go:39): failed to build crypto.PrivKey: received non-nil error from function "github.com/ipfs/go-ipfs/core/node".PrivateKey.func1 (github.com/ipfs/go-ipfs@v0.12.2/core/node/identity.go:18): private key in config does not match id: 12D3KooWKNoZSMa1BHtDGHtqrKvWg4k25rcHyq6uteQEXgybefGF != 12D3KooWPbLomJfPsuLNH3VWJJN24yZYDxDGtFnc8fBGbUWMgx8Y

Error: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".PstoreAddSelfKeys (github.com/ipfs/go-ipfs@v0.12.2/core/node/libp2p/libp2p.go:39): failed to build crypto.PrivKey: received non-nil error from function "github.com/ipfs/go-ipfs/core/node".PrivateKey.func1 (github.com/ipfs/go-ipfs@v0.12.2/core/node/identity.go:18): private key in config does not match id: 12D3KooWKNoZSMa1BHtDGHtqrKvWg4k25rcHyq6uteQEXgybefGF != 12D3KooWPbLomJfPsuLNH3VWJJN24yZYDxDGtFnc8fBGbUWMgx8Y

    at errorTemplate (/Applications/IPFS Desktop.app/Contents/Resources/

**Comment by hacdias** [comment] 2022-05-05 16:15
Duplicate of #2108

**Closed by hacdias** 2022-05-05 16:15 UTC
Labels: kind/bug, need/triage
