### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by thebaloa** [ipfs/ipfs-desktop#2244] opened 2022-08-28 21:54 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.22.0
- **Electron Version**: 19.0.8
- **Chrome Version**: 102.0.5005.148

**Error**

```
Error: Initializing daemon...
Kubo version: 0.14.0
Repo version: 12
System version: amd64/darwin
Golang version: go1.18.3

Error: lock /Users/jb/.ipfs/repo.lock: someone else has the lock

    at errorTemplate (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:78:49)
    at loadWindow (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:115:26)
    at module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:120:3)
    at startIpfsWithLogs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/daemon.js:165:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/daemon.js:194:17)
    at async startIpfs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:47:17)
    at async restartIpfs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:101:5)
    at async Object.restartIpfs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:34:5)
```

**Comment by hacdias** [comment] 2022-09-01 13:06
Duplicate of #2243. Please do not open multiple issues with the same content.

**Closed by hacdias** 2022-09-01 13:06 UTC
Labels: kind/bug, need/triage
