### ISSUE TITLE
Enabling IPNS pubsub via daemon flags

### ISSUE THREAD

**Issue by jakasi2** [ipfs/ipfs-desktop#1828] opened 2021-06-02 20:25 UTC
**OS:** Windows 10 Home 21H1 - build 19043.985
IPFS Desktop 0.15.0

- agent: go-ipfs v0.8.0
- UI: v2.12.2

**Bug description**
Cannot enable [IPNS pubsub](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipns-pubsub) with `--enable-namesys-pubsub` daemon flag. Flag is added as noted in [Which flags does IPFS Desktop boot with?](https://github.com/ipfs/ipfs-desktop#which-flags-does-ipfs-desktop-boot-with) .

The GUI (cube) flashes 2-3 times and then continues as nothing happened. Desired feature is still disabled - using `ipfs name pubsub state` . File `config.json` automatically resets to default configuration.

**To Reproduce**
The flag `--enable-namesys-pubsub` is added to a file `C:\Users\<user>\AppData\Roaming\IPFS Desktop\config.json` .
It doesn't matter in which position it is added. It only causes a more severe logdump if it is added directly after flag `--routing` . 

```
Command failed with exit code 1: C:\Users\<user>\AppData\Local\Programs\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs\ipfs.exe daemon --migrate --enable-gc --routing --enable-namesys-pubsub dhtclient
Error: expected 0 argument(s), got 1
```

**Expected behavior**
I am not sure what the expected behavior is, probablly the feature being enabled. I am trying to get familiar with IPNS PubSub atm.

**Logs**
Faulty log

```
2021-06-02T19:31:46.657Z info: [meta] logs can be found on C:\Users\<user>\AppData\Roaming\IPFS Desktop
2021-06-02T19:31:48.226Z info: [web ui] window ready
2021-06-02T19:31:48.226Z info: [web ui] navigate to /
2021-06-02T19:31:48.242Z info: [tray] starting
2021-06-02T19:31:48.459Z info: [tray] started
2021-06-02T19:31:48.460Z info: [ipfsd] start daemon STARTED
2021-06-02T19:31:48.947Z info: [daemon] removing api file
2021-06-02T19:31:49.899Z info: [ipfsd] start daemon FINISHED 1.4393155000004918s
2021-06-02T19:31:50.047Z info: [automatic gc] enabled
2021-06-02T19:31:50.048Z info: [pubsub] disabled
2021-06-02T19:31:50.060Z info: [ipfsd] stop daemon STARTED
2021-06-02T19:31:50.120Z info: [ipns over pubsub] disabled
2021-06-02T19:31:50.126Z info: [ipfs on path] no action taken
2021-06-02T19:31:50.126Z info: [launch on startup] disabled
2021-06-02T19:31:50.149Z info: [ipfsd] stop daemon FINISHED 0.08913480000011623s
2021-06-02T19:31:50.215Z info: [ipfsd] start daemon STARTED
2021-06-02T19:31:50.350Z info: [daemon] removing api file
2021-06-02T19:31:51.239Z info: [ipfsd] start daemon FINISHED 1.0239555999990553s
2021-06-02T19:31:52.582Z info: [updater] update not available
2021-06-02T19:33:42.005Z info: [ipfsd] stop daemon STARTED
```

**Additional context**
I am exploring a distributed app idea. Users would periodically upload/make available some data via IPFS. Service would use IPNS to log/retrieve the latest submission. IPNS PubSub would be used to notify the service of new IPNS mapping. For now, users would use IPFS Desktop as their gateway, since it provides a nice GUI, makes IPFS more familiar to them. Later go-ipfs daemon could be included in a seperate executable. As noted in the documentation both the users and the service provider need to have the IPNS PubSub enabled in order for it to work as intended.

**Comment by jakasi2** [comment] 2021-06-09 11:39
Thank you for the reply. I wasn't aware of the tray option. I found only CLI flag way of doing it. 

Since there are some issues with Electron tray and Linux distros it might not work on Linux. Is there any filtering of options/flag when the daemon is launched with IPFS Desktop. I tried the flags from the command line and it worked, it was just when the daemon was started via IPFS Desktop there was issues.

**Comment by andrasfuchs** [comment] 2021-06-09 12:03
I'm just a regular user and I'm not too familiar with CLI flags or IPFS on Linux, sorry!

**Comment by lidel** [comment] 2021-06-18 13:19
I'm closing this because the error was caused by manually changing config.json and introducing bug that way.
(note that `ipfs.exe daemon --migrate --enable-gc --routing --enable-namesys-pubsub dhtclient` has `dhtclient` which is not a valid parameter)

**Closed by lidel** 2021-06-18 13:19 UTC
Labels: need/triage
