### ISSUE TITLE
[gui error report] SyntaxError: C:\Users\yl4826\.ipfs\config: Unexpected token ']', ..."",

### ISSUE THREAD

**Issue by Hemanthkit** [ipfs/ipfs-desktop#2869] opened 2024-10-04 10:02 UTC
- **Desktop**: 0.38.0
- **OS**: win32 10.0.22631 x64
- **Electron**: 31.0.1
- **Chrome**: 126.0.6478.36

```
SyntaxError: C:\Users\yl4826\.ipfs\config: Unexpected token ']', ..."",

    ]
  },
 "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.readFileSync (C:\Users\yl4826\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\jsonfile\index.js:52:17)
    at readConfigFile (C:\Users\yl4826\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\config.js:68:13)
    at checkPorts (C:\Users\yl4826\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\config.js:332:18)
    at getIpfsd (C:\Users\yl4826\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:71:16)
    at async startDaemon (C:\Users\yl4826\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:210:17)
    at async startIpfs (C:\Users\yl4826\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:49:17)
    at async setupDaemon (C:\Users\yl4826\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:116:3)
    at async Promise.all (index 1)
    at async run (C:\Users\yl4826

**Comment by lidel** [comment] 2024-10-16 21:37
Duplicate of https://github.com/ipfs/ipfs-desktop/issues/2050#issuecomment-1074415162, try following steps described there.

**Closed by lidel** 2024-10-16 21:37 UTC
Labels: kind/bug, need/triage
