### ISSUE TITLE
Cannot connect to IPFS

### ISSUE THREAD

**Issue by shiloh92** [ipfs/ipfs-desktop#1829] opened 2021-06-05 11:34 UTC
No port changes made by me as far as I'm aware. Log into IPFS one day to find the updated version cannot connect. Tried installing manually, reinstalling etc. Got the web browser plugin and it connects fine. IPFS is connected, the desktop app shows that I am not, greyed out all options.
Seems a few others have the same issue as I noticed a Reddit post recently published about the same event. Used without issue with current settings, possibly due to update no longer able to access any of the files uploaded or any menu options.

**Comment by lidel** [comment] 2021-06-11 13:43
@shiloh92 
Is the built-in node provided by ipfs-desktop the only IPFS node you are running on your machine?
Namely, can browser extension connect to IPFS node even when you Quit ipfs-desktop?

**Comment by lidel** [comment] 2021-06-18 13:26
Closing this as it is most likely a duplicate of https://github.com/ipfs/ipfs-desktop/issues/1773#issuecomment-789294333 and will be fixed in next release when we update to go-ipfs 0.9.

**Closed by lidel** 2021-06-18 13:26 UTC
Labels: need/analysis, need/author-input, need/triage
