### ISSUE TITLE
Error: lock /home/user/snap/ipfs-desktop/37/.ipfs/repo.lock: permission denied

### ISSUE THREAD

**Issue by Openwrtfunboy** [ipfs/ipfs-desktop#2149] opened 2022-05-18 19:59 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.20.6
- **Electron Version**: 18.0.3
- **Chrome Version**: 100.0.4896.75

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.2
Repo version: 12
System version: amd64/linux
Golang version: go1.16.15

Error: lock /home/lul/snap/ipfs-desktop/37/.ipfs/repo.lock: permission denied

    at errorTemplate (/snap/ipfs-desktop/38/resources/app.asar/src/daemon/migration-prompt.js:78:49)
    at loadWindow (/snap/ipfs-desktop/38/resources/app.asar/src/daemon/migration-prompt.js:115:26)
    at module.exports (/snap/ipfs-desktop/38/resources/app.asar/src/daemon/migration-prompt.js:120:3)
    at startIpfsWithLogs (/snap/ipfs-desktop/38/resources/app.asar/src/daemon/daemon.js:165:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/snap/ipfs-desktop/38/resources/app.asar/src/daemon/daemon.js:194:17)
    at async startIpfs (/snap/ipfs-desktop/38/resources/app.asar/src/daemon/index.js:46:17)
    at async module.exports (/snap/ipfs-desktop/38/resources/app.asar/src/daemon/index.js:114:3)
    at async run (/snap/ipfs-desktop/38/resources/app.asar/src/index.js:86:5)
```

**Comment by hacdias** [comment] 2022-05-19 14:28
@lidel could you take a look at this issue? It seems quite similar to the context of #1906

**Comment by lidel** [comment] 2022-05-23 17:14
Nothing i can do, see https://github.com/ipfs/ipfs-desktop/issues/1906#issuecomment-1024734414

If someone familiar with Snap has time to investigate, that is appreciated, but I am closing this as duplicate of #1906

@Openwrtfunboy 
- if you want something that "just works", try  installing `.AppImage` instead. 
- if you  care about getting Snap to work, raise support in https://forum.snapcraft.io/t/ipfs-desktop-classic-review/28517?u=lidel

**Closed by lidel** 2022-05-23 17:14 UTC
Labels: kind/bug, need/triage

**Comment by lidel** [comment] 2022-06-23 11:22
in case this is useful for drive-by reader who found this issue from search, [snap forums state that](https://forum.snapcraft.io/t/ipfs-desktop-classic-review/28517/5?u=lidel):

> I wonder in this case perhaps if a snap got refreshed and so this <revision> in your upstream bug report may not be the active revision anymore (ie the user was running say revision 37 and so ~/snap/<snap-name>/current points to ~/snap/<snap-name>/37. Then the snap got refreshed to say 38 and so ~/snap/<snap-name>/current now points to ~/snap/<snap-name>/38 but the snap may still use the old 37 path (or vice-versa)).

> If this was the case this should now be avoided as snap refresh awareness is enabled by default IIRC which should stop a snap from refreshing to a new revision whilst it is already running.
