### ISSUE TITLE
Set IPFS_PATH in the client

### ISSUE THREAD

**Issue by zikunfan** [ipfs/ipfs-desktop#1866] opened 2021-07-02 03:19 UTC
**Is your feature request related to a problem? Please describe.**
When I start client app in windows/mac, it will choosing my `C:/` or `~/.ipfs` as default storing path.

**Describe the solution you'd like**
Can desktop app support to choose different disk/path when first start the app

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lidel** [comment] 2021-07-02 13:34
This is a duplicate of https://github.com/ipfs/ipfs-desktop/issues/1656, let's continue there

**Closed by lidel** 2021-07-02 13:34 UTC
Labels: need/triage
