### ISSUE TITLE
[0.20.1] Repo conversion fails -> Restart hangs at "IPFS is Starting" with no GUI

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#2017] opened 2022-03-08 13:36 UTC
- OS: Linux
 - Version of IPFS Desktop 0.20.1

**Describe the bug**
I'm updating my package for Arch, so I was testing the new 0.20.1 version.

On the first start it showed a Log-Window with the conversion, which failed due to bad ipv6 internet availability (or looked that way - error connection was "connection reset by peer" multiple times).

As it gave up, I stopped IPFS Desktop and started it again.

Now there's no GUI and the Status-Icon is grey.

When I click on it it shows a yellow status with "IPFS is Starting" message.

**To Reproduce**
Unsure

**Expected behavior**
Retry the conversion on each start until it succeeds.

**Additional context**

combined.log on the first start

```
2022-03-08T12:44:32.322Z info: [meta] logs can be found on /home/ruben/.config/IPFS Desktop
2022-03-08T12:44:35.240Z info: [web ui] window ready
2022-03-08T12:44:35.242Z info: [web ui] navigate to /
2022-03-08T12:44:35.255Z info: [tray] starting
2022-03-08T12:44:35.353Z info: [tray] started
2022-03-08T12:44:35.356Z info: [ipfsd] start daemon STARTED
2022-03-08T12:44:35.666Z info: [daemon] removing api file
2022-03-08T12:44:35.866Z info: [daemon] ipfs data store is migrating
```

combined.log on the second start.
```
2022-03-08T13:27:08.075Z info: [web ui] window hidden
```

There's no current log entry in the error.log, only one from month ago.

**Comment by lidel** [comment] 2022-03-14 20:47
@RubenKelevra do you have the original logs with "connection reset by peer" errors?
Unsure if this is a duplicate of https://github.com/ipfs/ipfs-desktop/issues/2023 or something ele.

**Comment by RubenKelevra** [comment] 2022-03-14 20:48
> @RubenKelevra do you have the original logs with "connection reset by peer" errors?
> Unsure if this is a duplicate of https://github.com/ipfs/ipfs-desktop/issues/2023 or something ele.

Nope. But it was just a TCP reset error.

**Comment by lidel** [comment] 2022-03-14 21:04
And there was no output after `[daemon] ipfs data store is migrating` ?

**Closed** 2022-03-14 23:59 UTC
Labels: kind/bug, need/triage, need/author-input
