### ISSUE TITLE
IPFS Desktop electron UI randomly breaks after visiting webUI in the browser

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs-desktop#1957] opened 2022-01-02 21:14 UTC
**Describe the bug**
IPFS Desktop webUI keeps breaking - showing an all-white screen (while interacting with the IPFS node via http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/ works fine)

**To Reproduce**
1. Open IPFS Desktop and browse menus - everything working fine
2. Also view desktop UI by visiting http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/
3. Go to drop down IPFS Desktop menu
4. Click on any of the status / files / etc pages
5. See all white IPFS desktop electron app UI - with no contents
6. Have to fully quit IPFS Desktop (not restart the node) to start working again

**Expected behavior**
IPFS Desktop should never show a weird, white, empty screen

**Screenshots**
![image](https://user-images.githubusercontent.com/618519/147889500-9cd9df58-f532-48cd-9b6d-57bad8556656.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome
 - Version: 96.0.4664.93 (Official Build) (x86_64)

Note - I'm also having a problem with https://github.com/ipfs/ipfs-webui/issues/1880 -- so while I haven't changed any of my default IPFS config - this may be related?

**Comment by lidel** [comment] 2022-01-14 14:46
Indeed, I think the underlying issue is that we are not awaiting on `window.webContents.loadURL` (it returns a promise).
The entire `launchWebUI` should be `async` and if we `await` on it where it is called that should remove the surface for racy bugs. 

@hacdias mind refactoring it?

**Comment by hacdias** [comment] 2022-02-09 16:55
**Note to self**: awaiting for `window.loadURL` fails with "ERR_FAILED (-2)" which is not very descriptive. I have to investigate (check preload and other scripts, see issue https://github.com/electron/electron/issues/18857).

**Comment by SgtPooki** [comment] 2023-10-31 23:02
Cannot reproduce this at this stage, I believe this is resolved in the latest version

**Closed by SgtPooki** 2023-10-31 23:02 UTC
Labels: kind/bug, area/macos, need/analysis
