### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by CountZer0** [ipfs/ipfs-desktop#2018] opened 2022-03-09 03:01 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.20.1
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.0
Repo version: 12
System version: amd64/windows
Golang version: go1.16.12
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 1 migrations, downloading.
Downloading migration: fs-repo-11-to-12...
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/v1.0.2/fs-repo-11-to-12_v1.0.2_windows-amd64.zip"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/v1.0.2/fs-repo-11-to-12_v1.0.2_windows-amd64.zip"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/v1.0.2/fs-repo-11-to-12_v1.0.2_windows-amd64.zip"
Error fetching: exceeded number of retries. last error was http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/v1.0.2/fs-repo-11-to-12_v1.0.2_windows-amd64.zip": dial tcp 209.94.90.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connect

**Comment by RubenKelevra** [comment] 2022-03-09 19:09
That's basically what happened to me in https://github.com/ipfs/ipfs-desktop/issues/2017. Just a bad connection for a while, and it won't retry on the next start.

**Comment by lidel** [comment] 2022-03-14 20:30
Duplicate of https://github.com/ipfs/ipfs-desktop/issues/2023

**Closed by lidel** 2022-03-14 20:30 UTC
Labels: kind/bug, need/triage
