### ISSUE TITLE
Pin status incorrect for files that were pinned recursively from folder.

### ISSUE THREAD

**Issue by MarcelInTO** [ipfs/ipfs-desktop#2237] opened 2022-08-24 15:33 UTC
- OS: Windows, Linux
- Version of IPFS Desktop: 2.15.1

If you recursively pin a folder, the files display will correctly show the pin status for the folder as pinned. 

However, if you look at the contents of the folder, there is no indication that the files have been pinned (as a result of the recursion). 

Furthermore, even though a pin status s displayed on the folder itself, it does not indicate whether that folder was locked recursively or not.

As a result, right now when navigating through a tree of files in the Files section,unless files were locked one by one, I don't have any way of telling if they are locked or not. I can one-by-one navigate upwards through the folder hierarchy and see if one of the parent folders was locked, but even I can't assume that that was a recursive lock...

**Expected behavior**
In the command line, if you recursively pin a folder, and then do an ls on a file in the folder, it correctly reports that it is pinned "indirect:" and tells you which CID is responsible for the indirect pin. This is useful and necessary information. I would expect the desktop client to:

1) Have the pin display on folders indicate whether that folder was locked recusively or not.
2) Display a pin status on files that were pinned indirectly because of one of their parent folders  (and maybe have a hover-over on the pin indicate the CID of the folder that initiated the pin)(

**Comment by hacdias** [comment] 2022-09-01 13:33
Duplicate of https://github.com/ipfs/ipfs-webui/issues/1736

**Closed by hacdias** 2022-09-01 13:33 UTC
Labels: kind/bug, need/triage

**Comment by trancephorm** [comment] 2026-03-25 06:26
the solution: https://guibo.vizio.biz/
