### ISSUE TITLE
[gui error report] Error: Exception 0xc0000005 0x8 0x0 0x0

### ISSUE THREAD

**Issue by mostafa0473** [ipfs/ipfs-desktop#2822] opened 2024-05-24 10:28 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32 6.1.7601
- **IPFS Desktop Version**: 0.35.1
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(
    at errorTemplate (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:78:49)
    at loadWindow (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:129:26)
    at showMigrationPrompt (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:134:3)
    at C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:158:25
    at Socket.listener (C:\Program Files\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:83:5)
    at Socket.emit (node:events:538:35)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by lidel** [comment] 2024-06-12 14:33
Duplicate of https://github.com/ipfs/ipfs-desktop/issues/2823, let's continue there

**Closed by lidel** 2024-06-12 14:33 UTC
Labels: kind/bug, need/triage
