### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by OwenLittleWhite** [ipfs/ipfs-desktop#2097] opened 2022-04-08 03:19 UTC
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.20.4
- **Electron Version**: 17.2.0
- **Chrome Version**: 98.0.4758.109

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: amd64/windows
Golang version: go1.16.12
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 1 migrations, downloading.
Downloading migration: fs-repo-11-to-12...
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Error fetching: exceeded number of retries. last error was http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions": dial tcp 108.160.162.31:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Fetching with IPFS: "fs-repo-11-to-12/versions"
Error fetching: context deadline exceeded
could not get latest version of migration fs-repo-11-to-12: 2 errors occurred:
	* exceeded number of

**Comment by hacdias** [comment] 2022-04-08 06:32
Duplicate of #2035

**Closed by hacdias** 2022-04-08 06:32 UTC
Labels: kind/bug, need/triage
