### ISSUE TITLE
Your programs version (7) is lower than your repos (15)

### ISSUE THREAD

**Issue by xiang10000** [ipfs/ipfs-desktop#2853] opened 2024-08-18 09:24 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.6.1
- **Electron Version**: 4.0.0
- **Chrome Version**: 69.0.3497.106

**Error**

```
Error: Command failed: C:\Users\91121\AppData\Local\Programs\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs-dep\go-ipfs\ipfs.exe daemon --migrate=true --routing=dhtclient --enable-gc=true
Error: Your programs version (7) is lower than your repos (15).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.

Initializing daemon...
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/windows
Golang version: go1.11.1

    at makeError (C:\Users\91121\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\91121\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by lidel** [comment] 2024-09-11 20:18
Duplicate of https://github.com/ipfs/ipfs-desktop/issues/2854#issuecomment-2344622872
Please follow suggestion from that comment.

**Closed by lidel** 2024-09-11 20:18 UTC
