### ISSUE TITLE
Please gpg sign release

### ISSUE THREAD

**Issue by jonathancross** [ipfs/ipfs-desktop#2878] opened 2024-10-17 01:09 UTC
I didn't see signature files with the latest downloads meaning that users are just trusting github.
Would be much better if devs signed binaries (and release tags) so users could have more confidence in the builds.

**Comment by lidel** [comment] 2024-10-17 19:36
Marking as duplicate of https://github.com/ipfs/ipfs-desktop/issues/2867

Please see my note how current artifacts are built (fully on github CI) and post your threat model, and ideas on what should be improved and why on that issue :pray:

**Closed by lidel** 2024-10-17 19:36 UTC
Labels: need/triage
