### ISSUE TITLE
IPFS Desktop installs itself at arbitrary location

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-desktop#1779] opened 2021-03-10 15:22 UTC
- OS: Windows
- Version of IPFS Desktop [e.g. 0.11.1] : 0.14.0

**Describe the bug**
When IPFS Desktop updates, it installs itself at an arbitrary location then adds itself to start-up programs. This causes problems with package managers and users' setup. For example, while I do want the IPFS Desktop entry in the Task Manager, if another one is added at a different location, then there's unexpected behaviours. Two different versions can launch at the same time.

**To Reproduce**
> Steps to reproduce the behavior:
1. Update IPFS Desktop

**Expected behavior**
IPFS Desktop should do an in-place update instead of installing itself at an arbitrary location.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by lidel** [comment] 2021-05-04 22:19
IIUC this is a duplicate of  https://github.com/ipfs/ipfs-desktop/issues/1656, so let's continue there.
Feel free to reopen if you believe this is a separate issue (but please elaborate why).

**Closed by lidel** 2021-05-04 22:19 UTC
Labels: need/triage
