### ISSUE TITLE
Service Already Present

### ISSUE THREAD

**Issue by Jan877** [ipfs/ipfs-desktop#1873] opened 2021-07-18 18:40 UTC
- OS: Windows 10
 - Version of IPFS Desktop 2.12.4

**Describe the bug**
By mistake I deleted Pinata from my Pinning Services in IPFS and now I can't add it again. When I try adding Pinata I get a message "Service Already Present" (see attached file). I have filed a support question, but nothing has happened..

**To Reproduce**
1. Go to Settings in IPFS.
2. Click on Add Service
3. Select Pinata.
4. Enter API endpoint and Secret Access Token (the JWT-code)
5. Message Service Already Present is shown.
6. Pinata is not added as Pinning Service-

**Expected behavior**
I expect to be able to see Pinata as one of the Pinning Services.

**Screenshots**
<img width="960" alt="Service Already Present" src="https://user-images.githubusercontent.com/44270690/126078477-301f4cd2-3aa1-4d6c-bb73-9a997ab9718f.png">

**Additional context**

**Comment by unbeatable-101** [comment] 2021-07-19 04:28
I don't know what the issue is, but try giving it the nickname Pinata1 or something like that

**Comment by lidel** [comment] 2021-08-06 13:27
This is duplicate of https://github.com/ipfs/ipfs-webui/issues/1816, let's continue there.

**Closed by lidel** 2021-08-06 13:27 UTC
Labels: need/triage
