### ISSUE TITLE
Reduce clutter of files and folders and move data to the local profile folder (Windows)

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1862] opened 2021-06-25 13:10 UTC
**Is your feature request related to a problem? Please describe.**
If a user installs IPFS Desktop on Windows, it will create multiple folders:

`%AppData%\Roaming\IPFS Desktop`
`%USERPROFILE%\.ipfs`
`%USERPROFILE%\.ipfs-desktop`

That's pretty unintuitive where what data will be stored and why.

**Describe the solution you'd like**
Let IPFS Desktop create a single folder in `%AppData%` and move the rest of the folders below it. 

**Additional context**

Not sure if we should really use the Roaming folder, depending on the size of the data stored and cached in IPFS it could slow down logins on mobile devices or secondary desktops in a domain significantly. I think since IPFS addresses nodes and not user profiles, we might want to move the folder to local, which means on secondary desktops or mobile devices, the folder won't be fetched. Additionally, it won't be stored in the remote profile on the domain server, but instead on the local computer only.

**Comment by lidel** [comment] 2021-07-02 13:35
This is a duplicate of https://github.com/ipfs/ipfs-desktop/issues/1656, let's continue there.

**Closed by lidel** 2021-07-02 13:35 UTC
Labels: need/triage
