### ISSUE TITLE
IPFS-Desktop update loop is broken on macOS

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-desktop#1995] opened 2022-02-28 17:18 UTC
- OS: macOS Monterey 12.2.1 (21D62)
 - Version of IPFS Desktop Version 0.18.1 (0.18.1)
   -  UI v2.13.0 ([44a46ba](https://github.com/ipfs/ipfs-webui/commit/44a46ba)) ![ipfs-desktop version v2.13.0 (44a46ba)](https://user-images.githubusercontent.com/1173416/156025735-6435180a-6ffd-4fe3-adc9-30254e1b0d75.png)
- go-ipfs version: `ipfs version 0.12.0`

**Describe the bug**
Starting IPFS-Desktop results in a popup window indicating that a restart is required in order to update: 
![image](https://user-images.githubusercontent.com/1173416/156025928-5b69717f-19c9-43e8-8151-56ade0b4e0ce.png)

**To Reproduce**
1. Download old version of ipfs-desktop
2. Start go-ipfs daemon in terminal
3. start ipfs-desktop
4. See popup msg about update, click restart
5. go-ipfs daemon is killed, ipfs desktop update popup goes away
6. Nothing is updated.. pattern repeats over and over

**Expected behavior**
The update should be performed successfully

**Screenshots**
See video of problem here: https://user-images.githubusercontent.com/1173416/156026282-5d0312f4-3282-48b2-ad96-da0d635a9a07.mp4

**Additional context**

[combined.log](https://github.com/ipfs/ipfs-desktop/files/8155300/combined.log)
[error.log](https://github.com/ipfs/ipfs-desktop/files/8155299/error.log)

**Comment by lidel** [comment] 2022-02-28 17:37
This sounds like a duplicate of https://github.com/ipfs/ipfs-desktop/issues/1980 –  sadly, I don't see how we can fix broken  0.18.1 installations.

The only move we have is to make it easier for users to discover the instruction to manually update to 0.19.3, but lmk if you have better ideas :pray:

**Comment by lidel** [comment] 2022-03-03 17:55
See  https://github.com/ipfs/ipfs-desktop/issues/1980

**Closed by lidel** 2022-03-03 17:55 UTC
Labels: kind/bug, area/macos, need/author-input, status/duplicate
