### ISSUE TITLE
IPFS Desktop shutdown unexpectedly.

### ISSUE THREAD

**Issue by Proto133** [ipfs/ipfs-desktop#1861] opened 2021-06-24 21:20 UTC
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.15.1
- **Electron Version**: 12.0.5
- **Chrome Version**: 89.0.4389.128

**Error**

```
Error: EACCES: permission denied, open '/home/proto/snap/ipfs-desktop/25/.config/IPFS Desktop/config.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.writeFileSync (fs.js:1467:35)
    at ElectronStore._write (/snap/ipfs-desktop/25/resources/app.asar/node_modules/conf/dist/source/index.js:370:16)
    at ElectronStore.set store [as store] (/snap/ipfs-desktop/25/resources/app.asar/node_modules/conf/dist/source/index.js:296:14)
    at ElectronStore.set (/snap/ipfs-desktop/25/resources/app.asar/node_modules/conf/dist/source/index.js:189:20)
    at Timeout.existsAndUpdate [as _onTimeout] (/snap/ipfs-desktop/25/resources/app.asar/src/npm-on-ipfs/index.js:38:11)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by Proto133** [comment] 2021-06-24 21:22
I am fine just restarting it. I just figured I would report the issue in case it helps the development somehow.

**Comment by lidel** [comment] 2021-09-08 13:45
@Proto133  I am trying to understand if this is a duplicate of https://github.com/ipfs/ipfs-desktop/issues/1906 or a different bug
- did the issue go away after the restart? 
- do you have IPFS Daeon snap istalled as well, like the person from https://github.com/ipfs/ipfs-desktop/issues/1906?

**Comment by Proto133** [comment] 2021-09-08 16:34
I just purged ipfs then, reinstalled and everything is good now. (The shear restart of the daemon did nothing).

**Comment by lidel** [comment] 2021-09-24 13:08
Fair enough. Please comment in https://github.com/ipfs/ipfs-desktop/issues/1906 or open a new issue if the problem comes back.

**Closed by lidel** 2021-09-24 13:08 UTC
Labels: need/triage, need/author-input
